version: '3'

services:
  mongodb:
    image: 'bitnami/mongodb:7.0.8'
    ports: 
      - '27017:27017'
    restart: on-failure
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_USERNAME=myuser
      - MONGODB_PASSWORD=mypassword
      - MONGODB_DATABASE=mydatabase
